apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    alm-examples: |-
      [
        {
          "apiVersion": "humio.partners.ibm.com/v1alpha1",
          "kind": "CloudPakHumioCluster",
          "metadata": {
            "name": "cphumio"
          },
          "spec": {
            "BedRockSelfSignedCert": false,
            "OidcGroupsClaim": "groupIds",
            "OidcUsernameClaim": "email",
            "humioClusterSpec": {
              "dataVolumePersistentVolumeClaimSpecTemplate": {
                "accessModes": [
                  "ReadWriteOnce"
                ],
                "resources": {
                  "requests": {
                    "storage": "100Gi"
                  }
                }
              },
              "environmentVariables": {},
              "helperImage": "humio/humio-operator-helper:0.0.8",
              "image": "humio/humio-core:1.18.1",
              "nodeCount": 3,
              "targetReplicationFactor": 3
            },
            "strimzi": {
              "createKafkaCluster": false
            }
          }
        }
      ]
    capabilities: Basic Install
    operators.operatorframework.io/builder: operator-sdk-v1.0.0
    operators.operatorframework.io/project_layout: helm.sdk.operatorframework.io/v1
  name: humioforibmcloudpakoperator.v0.0.1
  namespace: placeholder
spec:
  apiservicedefinitions: {}
  customresourcedefinitions:
    owned:
    - description: CloudPak-Integrated Humio Chart
      kind: CloudPakHumioCluster
      name: cloudpakhumioclusters.humio.partners.ibm.com
      version: v1alpha1
    required:
    - description: Humio Cluster
      kind: HumioCluster
      name: humioclusters.core.humio.com
      version: v1alpha1
  description: Humio IBM Cloud Pak® Integration Operator
  displayName: Humio for IBM Cloud Pak®
  icon:
  - base64data: ""
    mediatype: ""
  install:
    spec:
      clusterPermissions:
      - rules:
        - apiGroups:
          - ""
          resources:
          - namespaces
          verbs:
          - get
        - apiGroups:
          - ""
          resources:
          - secrets
          verbs:
          - '*'
        - apiGroups:
          - ""
          resources:
          - events
          verbs:
          - create
        - apiGroups:
          - humio.partners.ibm.com
          resources:
          - cloudpakhumioclusters
          - cloudpakhumioclusters/status
          - cloudpakhumioclusters/finalizers
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - kafka.strimzi.io
          resources:
          - kafkas
          verbs:
          - '*'
        - apiGroups:
          - core.humio.com
          resources:
          - humioclusters
          - humiorepositories
          verbs:
          - '*'
        - apiGroups:
          - humio.partners.ibm.com
          resources:
          - cloudpakhumioclusters
          - cloudpakhumioclusters/status
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - core.humio.com
          resources:
          - humioclusters
          verbs:
          - '*'
        - apiGroups:
          - kafka.strimzi.io
          resources:
          - kafkas
          verbs:
          - '*'
        - apiGroups:
          - integrations.sdk.management.ibm.com
          resources:
          - oidcclientregistrations
          - navmenuentries
          verbs:
          - '*'
        - apiGroups:
          - networking.k8s.io
          resources:
          - ingresses
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        serviceAccountName: cphumio-manager
      deployments:
      - name: cphumio-controller-manager
        spec:
          replicas: 1
          selector:
            matchLabels:
              control-plane: controller-manager
          strategy: {}
          template:
            metadata:
              labels:
                control-plane: controller-manager
            spec:
              containers:
              - args:
                - --enable-leader-election
                - --leader-election-id=humioforibmcloudpakoperator
                image: quay.io/zach_robinson/ibm-cp4m-humio-operator:0.0.1
                imagePullPolicy: Always
                name: manager
                resources:
                  limits:
                    cpu: 100m
                    memory: 256Mi
                  requests:
                    cpu: 100m
                    memory: 64Mi
              serviceAccountName: cphumio-manager
              terminationGracePeriodSeconds: 10
      permissions:
      - rules:
        - apiGroups:
          - ""
          resources:
          - configmaps
          verbs:
          - get
          - list
          - watch
          - create
          - update
          - patch
          - delete
        - apiGroups:
          - ""
          resources:
          - events
          verbs:
          - create
          - patch
        serviceAccountName: cphumio-manager
    strategy: deployment
  installModes:
  - supported: false
    type: OwnNamespace
  - supported: false
    type: SingleNamespace
  - supported: false
    type: MultiNamespace
  - supported: true
    type: AllNamespaces
  keywords:
  - Humio
  - IBM
  - CloudPak
  - CP4MCM
  - Watson
  - AIOPS
  - AI-OPS
  - Logging
  - Monitoring
  - Management
  links:
  - name: Humioforibmcloudpakoperator
    url: https://humioforibmcloudpakoperator.domain
  maintainers:
  - email: zachrobinson@ibm.com
    name: Zach Robinson
  maturity: alpha
  provider:
    name: IBM
    url: IBM.com
  version: 0.0.1
