# permissions for end users to view cloudpakhumioclusters.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: cloudpakhumiocluster-viewer-role
rules:
  - apiGroups:
      - charts.my.domain
    resources:
      - cloudpakhumioclusters
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - charts.my.domain
    resources:
      - cloudpakhumioclusters/status
    verbs:
      - get
