apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    alm-examples: '[]'
    capabilities: Basic Install
    operators.operatorframework.io/builder: operator-sdk-v1.0.0
    operators.operatorframework.io/project_layout: helm.sdk.operatorframework.io/v1
  name: humioforibmcloudpakoperator.vX.Y.Z
  namespace: placeholder
spec:
  apiservicedefinitions: { }
  customresourcedefinitions:
    owned:
      - description: CloudPak-Integrated Humio Chart
        kind: CloudPakHumioCluster
        name: cloudpakhumioclusters.humio.partners.ibm.com
        version: v1alpha1
    required:
      - description: defines a new entry in the primary CloudPak Nav-Menu. This product is not deployable standalone and is part of the LICCR already accepted
        kind: NavMenuEntry
        name: navmenuentries.integrations.sdk.management.ibm.com
        version: v1beta1
      - description: manages registration of an OIDC client with IAM
        kind: OidcClientRegistration
        name: oidcclientregistrations.integrations.sdk.management.ibm.com
        version: v1beta1
      - description: policy-based generator of LIC resources for K8S SIG applications. This product is not deployable standalone and is part of the LICCR already accepted
        kind: ApplicationLaunchInContextPolicy
        name: applicationlaunchincontextpolicies.integrations.sdk.management.ibm.com
        version: v1beta1
      - description: Humio Cluster
        kind: HumioCluster
        name: humioclusters.core.humio.com
        version: v1alpha1
      - description: Humio Repo
        kind: HumioRepository
        name: humiorepositories.core.humio.com
        version: v1alpha1
      - description: Humio Ingest Token
        kind: HumioIngestToken
        name: humioingesttokens.core.humio.com
        version: v1alpha1
  description: Humio IBM Cloud Pak® Integration Operator
  displayName: Humio for IBM Cloud Pak®
  icon:
    - base64data: ""
      mediatype: ""
  install:
    spec:
      deployments: null
    strategy: ""
  installModes:
    - supported: true
      type: OwnNamespace
    - supported: true
      type: SingleNamespace
    - supported: false
      type: MultiNamespace
    - supported: true
      type: AllNamespaces
  keywords:
    - Humio
    - IBM
    - CloudPak
    - CP4MCM
    - Watson
    - AIOPS
    - AI-OPS
    - Logging
    - Monitoring
    - Management
  links:
    - name: Humioforibmcloudpakoperator
      url: https://humioforibmcloudpakoperator.domain
  maintainers:
    - email: zachrobinson@ibm.com
      name: Zach Robinson
  maturity: alpha
  provider:
    name: IBM
    url: IBM.com
  version: 0.0.0
