apiVersion: humio.partners.ibm.com/v1alpha1
kind: CloudPakHumioCluster
metadata:
  name: cloudpakhumiocluster-sample
spec:
  humioClusterSpec:
    image: "humio/humio-core:1.18.1"
    helperImage: "humio/humio-operator-helper/1.18.1"
    nodeCount: 3
    targetReplicationFactor: 3
    dataVolumePersistentVolumeClaimSpecTemplate:
      accessModes:
        - ReadWriteOnce
      resources:
        requests:
          storage: 100Gi
    environmentVariables: {}
  OidcUsernameClaim: "email"
  OidcGroupsClaim: "groupIds"
  BedRockSelfSignedCert: false
  strimzi:
    createKafkaCluster: false
  
  
