apiVersion: core.humio.com/v1alpha1
kind: HumioCluster
metadata:
  name: {{ include "CloudPakHumioCluster.fullname" . }}
  labels: {{ include "CloudPakHumioCluster.labels" . | nindent 4 }}
spec: {{ .Values.humioClusterSpec | toYaml | nindent 2 }}
  environmentVariables:
    - name: "AUTHENTICATION_METHOD"
      value: "oauth"
    - name: "AUTO_CREATE_USER_ON_SUCCESSFUL_LOGIN"
      value: "true"
    - name: "OIDC_USERNAME_CLAIM"
      value: "email" {{/* TODO use uid instead if possible */}}
    - name: "OIDC_PROVIDER"
      valueFrom:
        secretKeyRef:
          name: {{ include "CloudPakHumioCluster.fullname" . }}-oidc
          key: OIDC_ISSUER_URL
    - name: "OIDC_OAUTH_CLIENT_ID"
      valueFrom:
        secretKeyRef:
          name: {{ include "CloudPakHumioCluster.fullname" . }}-oidc
          key: CLIENT_ID
    - name: "OIDC_OAUTH_CLIENT_SECRET"
      valueFrom:
        secretKeyRef:
          name: {{ include "CloudPakHumioCluster.fullname" . }}-oidc
          key: CLIENT_SECRET
    {{ if .Values.strimzi.createKafkaCluster }}
    - name: "ZOOKEEPER_URL"
      value: {{ include "CloudPakHumioCluster.fullname" . }}-zookeeper-client:2181
    - name: "KAFKA_SERVERS"
      value: {{ include "CloudPakHumioCluster.fullname" . }}-kafka-brokers:9092"
    {{ end }}