apiVersion: core.humio.com/v1alpha1
kind: HumioCluster
metadata:
  name: {{ include "CloudPakHumioCluster.fullname" . }}
  namespace: cp4m
  labels: {{ include "CloudPakHumioCluster.labels" . | nindent 4 }}
spec: {{ .Values.humioClusterSpec | toYaml | nindent 2 }}
  environmentVariables:
    {{ if .Values.humioClusterSpec.environmentVariables }}
    {{ .Values.humioClusterSpec.environmentVariables | toYaml | nindent 4 }}
    {{ end }}
    - name: "AUTHENTICATION_METHOD"
      value: "oauth"
    - name: "AUTO_CREATE_USER_ON_SUCCESSFUL_LOGIN"
      value: "true"
    - name: "AUTO_UPDATE_GROUP_MEMBERSHIPS_ON_SUCCESSFUL_LOGIN"
      value: "true"
    - name: "OIDC_USERNAME_CLAIM"
      value: {{ .Values.OidcUsernameClaim }}
    - name: "OIDC_GROUPS_CLAIM"
      value: {{ .Values.OidcGroupsClaim }}
    - name: "OIDC_PROVIDER"
      valueFrom:
        secretKeyRef:
          name: {{ include "CloudPakHumioCluster.fullname" . }}-oidc
          key: OIDC_ISSUER_URL
    - name: "OIDC_OAUTH_CLIENT_ID"
      valueFrom:
        secretKeyRef:
          name: {{ include "CloudPakHumioCluster.fullname" . }}-oidc
          key: CLIENT_ID
    - name: "OIDC_OAUTH_CLIENT_SECRET"
      valueFrom:
        secretKeyRef:
          name: {{ include "CloudPakHumioCluster.fullname" . }}-oidc
          key: {{ include "clientSecret" . }}
    {{ if .Values.strimzi.createKafkaCluster }}
    - name: "ZOOKEEPER_URL"
      value: {{ include "CloudPakHumioCluster.fullname" . }}-zookeeper-client:2181
    - name: "KAFKA_SERVERS"
      value: {{ include "CloudPakHumioCluster.fullname" . }}-kafka-brokers:9092
    {{ end }}
    {{ if .Values.BedRockSelfSignedCert }}
    - name: HUMIO_JVM_ARGS
      value: -Djavax.net.ssl.trustStore=/truststore/truststore.jks -Djavax.net.ssl.trustStorePassword=changeit
  extraVolumes:
    - name: truststore
      secret:
        secretName: truststore
  extraHumioVolumeMounts:
    - mountPath: /truststore
      name: truststore
    {{ end }}
  ingress:
    enabled: true
    tls: false
    controller: nginx
    annotations:
      kubernetes.io/ingress.class: ibm-icp-management
  path: "/humio"