apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "CloudPakHumioCluster.fullname" . }}
  labels: {{ include "CloudPakHumioCluster.labels" . | nindent 4 }}
  annotations:
    kubernetes.io/ingress.class: ibm-icp-management
spec:
  rules:
  - http:
      paths:
        - backend:
            service:
              name: {{ include "CloudPakHumioCluster.fullname" . }}
              port:
                number: 8080
          path: /humio
          pathType: ImplementationSpecific

