{{ if .Values.strimzi.createKafkaCluster }}
apiVersion: {{ .Values.strimzi.apiVersion }}
kind: Kafka
metadata:
  name: {{ include "CloudPakHumioCluster.fullname" . }}
  labels: {{ include "CloudPakHumioCluster.labels" . | nindent 4 }}
spec: {{ .Values.strimzi.spec | toYaml | nindent 2 }}
  {{ end }}