apiVersion: integrations.sdk.management.ibm.com/v1beta1
kind: OidcClientRegistration
metadata:
  name: {{ include "CloudPakHumioCluster.fullname" . }}
  labels: {{ include "CloudPakHumioCluster.labels" . | nindent 4 }}
spec:
  registration:
    scope: "openid profile {{ .Values.OidcUsernameClaim }} {{ .Values.OidcGroupsClaim }}"
    post_logout_redirect_uris:
      - https://{{ include "CloudPakHumioCluster.routeurlreference" . }}
    trusted_uri_prefixes:
      - https://{{ include "CloudPakHumioCluster.routeurlreference" . }}
      - https://{{ include "CloudPakHumioCluster.routeurlreference" . }}:443
    redirect_uris:
      - https://{{ include "CloudPakHumioCluster.routeurlreference" . }}/auth/oidc
    client_secret:
      secretName: {{ include "CloudPakHumioCluster.fullname" . }}-oidc
      secretKey: CLIENT_SECRET
    apply_client_secret: true